apiVersion: v1
kind: ReplicationController
metadata:
  name: q3a-server
spec:
  replicas: 3
  selector:
    app: q3a-server
  template:
    metadata:
      name: q3a-server
      labels:
        app: q3a-server
    spec:
      containers:
        - name: q3a-server
          image: asia.gcr.io/${PROJECT_ID}/q3a-server:${CIRCLE_SHA1}
          ports:
            - containerPort: 27960
              protocol: UDP
